### ISSUE TITLE
Android crash: PhysicalExamActivity.java line 175 

### ISSUE THREAD

**Issue by Sidintelehealth** [Intelehealth/Android-Mobile-Client#781]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.intelehealth.client/io.intelehealth.client.activities.physical_exam_activity.PhysicalExamActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2883)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by Sidintelehealth** [comment]
This was happening in the playstore version.
